import React from 'react'
import { Cardd } from './Cardd'

export const FlagGallery = () => {
    return (
        <div className='grid grid-cols-4 gap-5 mx-3 pt-20'>
            <Cardd nameTag="Afghanistan" />
            <Cardd nameTag="Albania" />
            <Cardd nameTag="Algeria" />
            <Cardd nameTag="Andorra" />
            <Cardd nameTag="Angola" />
            <Cardd nameTag="Antigua and Barbuda" />
            <Cardd nameTag="Argentina" />
            <Cardd nameTag="Armenia" />
            <Cardd nameTag="Australia" />
            <Cardd nameTag="Austria" />
            <Cardd nameTag="Azerbaijan" />
            <Cardd nameTag="Bahamas" />
            <Cardd nameTag="Bahrain" />
            <Cardd nameTag="Bangladesh" />
            <Cardd nameTag="Barbados" />
            <Cardd nameTag="Belarus" />
            <Cardd nameTag="Belgium" />
            <Cardd nameTag="Belize" />
            <Cardd nameTag="Benin" />
            <Cardd nameTag="Bhutan" />
            <Cardd nameTag="Bolivia" />
            <Cardd nameTag="Bosnia and Herzegovina" />
            <Cardd nameTag="Botswana" />
            <Cardd nameTag="Brazil" />
            <Cardd nameTag="Brunei" />
            <Cardd nameTag="Bulgaria" />
            <Cardd nameTag="Burkina Faso" />
            <Cardd nameTag="Burundi" />
            <Cardd nameTag="Cape Verde" />
            <Cardd nameTag="Cambodia" />
            <Cardd nameTag="Cameroon" />
            <Cardd nameTag="Canada" />
            <Cardd nameTag="Central African Republic" />
            <Cardd nameTag="Chad" />
            <Cardd nameTag="Chile" />
            <Cardd nameTag="China" />
            <Cardd nameTag="Colombia" />
            <Cardd nameTag="Comoros" />
            <Cardd nameTag="Cook Islands" />
            <Cardd nameTag="Costa Rica" />
            <Cardd nameTag="Croatia" />
            <Cardd nameTag="Cuba" />
            <Cardd nameTag="Cyprus" />
            <Cardd nameTag="Czech Republic"/>
            <Cardd nameTag="Democratic Republic of the Congo" />
            <Cardd nameTag="Denmark" />
            <Cardd nameTag="Djibouti" />
            <Cardd nameTag="Dominica" />
            <Cardd nameTag="Dominican Republic" />
            <Cardd nameTag="Ecuador" />
            <Cardd nameTag="Egypt" />
            <Cardd nameTag="El Salvador" />
            <Cardd nameTag="Equatorial Guinea" />
            <Cardd nameTag="Eritrea" />
            <Cardd nameTag="Estonia" />
            <Cardd nameTag="Eswatini" />
            <Cardd nameTag="Ethiopia" />
            <Cardd nameTag="Fiji" />
            <Cardd nameTag="Finland" />
            <Cardd nameTag="France" />
            <Cardd nameTag="Gabon" />
            <Cardd nameTag="Gambia" />
            <Cardd nameTag="Georgia" />
            <Cardd nameTag="Germany" />
            <Cardd nameTag="Ghana" />
            <Cardd nameTag="Greece" />
            <Cardd nameTag="Grenada" />
            <Cardd nameTag="Guatemala" />
            <Cardd nameTag="Guinea" />
            <Cardd nameTag="Guinea-Bissau" />
            <Cardd nameTag="Guyana" />
            <Cardd nameTag="Haiti" />
            <Cardd nameTag="Honduras" />
            <Cardd nameTag="Hungary" />
            <Cardd nameTag="Iceland" />
            <Cardd nameTag="India" />
            <Cardd nameTag="Indonesia" />
            <Cardd nameTag="Iran" />
            <Cardd nameTag="Iraq" />
            <Cardd nameTag="Ireland" />
            <Cardd nameTag="Israel" />
            <Cardd nameTag="Italy" />
            <Cardd nameTag="Ivory Coast"/>
            <Cardd nameTag="Jamaica" />
            <Cardd nameTag="Japan" />
            <Cardd nameTag="Jordan" />
            <Cardd nameTag="Kazakhstan" />
            <Cardd nameTag="Kenya" />
            <Cardd nameTag="Kiribati" />
            <Cardd nameTag="Kosovo" />
            <Cardd nameTag="Kuwait" />
            <Cardd nameTag="Kyrgyzstan" />
            <Cardd nameTag="Laos" />
            <Cardd nameTag="Latvia" />
            <Cardd nameTag="Lebanon" />
            <Cardd nameTag="Lesotho" />
            <Cardd nameTag="Liberia" />
            <Cardd nameTag="Libya" />
            <Cardd nameTag="Liechtenstein" />
            <Cardd nameTag="Lithuania" />
            <Cardd nameTag="Luxembourg" />
            <Cardd nameTag="Madagascar" />
            <Cardd nameTag="Malawi" />
            <Cardd nameTag="Malaysia" />
            <Cardd nameTag="Maldives" />
            <Cardd nameTag="Mali" />
            <Cardd nameTag="Malta" />
            <Cardd nameTag="Marshall Islands" />
            <Cardd nameTag="Mauritania" />
            <Cardd nameTag="Mauritius" />
            <Cardd nameTag="Mexico" />
            <Cardd nameTag="Micronesia" />
            <Cardd nameTag="Moldova" />
            <Cardd nameTag="Monaco" />
            <Cardd nameTag="Mongolia" />
            <Cardd nameTag="Montenegro" />
            <Cardd nameTag="Morocco" />
            <Cardd nameTag="Mozambique" />
            <Cardd nameTag="Myanmar" />
            <Cardd nameTag="Namibia" />
            <Cardd nameTag="Nauru" />
            <Cardd nameTag="Nepal" />
            <Cardd nameTag="Netherlands" />
            <Cardd nameTag="New Zealand" />
            <Cardd nameTag="Nicaragua" />
            <Cardd nameTag="Niger" />
            <Cardd nameTag="Nigeria" />
            <Cardd nameTag="North Korea" />
            <Cardd nameTag="North Macedonia" />
            <Cardd nameTag="Norway" />
            <Cardd nameTag="Oman" />
            <Cardd nameTag="Pakistan" />
            <Cardd nameTag="Palau" />
            <Cardd nameTag="Palestine" />
            <Cardd nameTag="Panama" />
            <Cardd nameTag="Papua New Guinea" />
            <Cardd nameTag="Paraguay" />
            <Cardd nameTag="Peru" />
            <Cardd nameTag="Philippines" />
            <Cardd nameTag="Poland" />
            <Cardd nameTag="Portugal" />
            <Cardd nameTag="Qatar" />
            <Cardd nameTag="Republic of the Congo" />
            <Cardd nameTag="Romania" />
            <Cardd nameTag="Russia" />
            <Cardd nameTag="Rwanda" />
            <Cardd nameTag="Saint Kitts and Nevis" />
            <Cardd nameTag="Saint Lucia" />
            <Cardd nameTag="Saint Vincent and the Grenadines" />
            <Cardd nameTag="Samoa" />
            <Cardd nameTag="San Marino" />
            <Cardd nameTag="Sao Tome and Principe" />
            <Cardd nameTag="Saudi Arabia" />
            <Cardd nameTag="Senegal" />
            <Cardd nameTag="Serbia" />
            <Cardd nameTag="Seychelles" />
            <Cardd nameTag="Sierra Leone" />
            <Cardd nameTag="Singapore" />
            <Cardd nameTag="Slovakia" />
            <Cardd nameTag="Slovenia" />
            <Cardd nameTag="Solomon Islands" />
            <Cardd nameTag="Somalia" />
            <Cardd nameTag="South Africa" />
            <Cardd nameTag="South Korea" />
            <Cardd nameTag="South Sudan" />
            <Cardd nameTag="Spain" />
            <Cardd nameTag="Sri Lanka" />
            <Cardd nameTag="Sudan" />
            <Cardd nameTag="Suriname" />
            <Cardd nameTag="Sweden" />
            <Cardd nameTag="Switzerland" />
            <Cardd nameTag="Syria" />
            <Cardd nameTag="Taiwan" />
            <Cardd nameTag="Tajikistan" />
            <Cardd nameTag="Tanzania" />
            <Cardd nameTag="Thailand" />
            <Cardd nameTag="Timor-Leste" />
            <Cardd nameTag="Togo" />
            <Cardd nameTag="Tonga" />
            <Cardd nameTag="Trinidad and Tobago" />
            <Cardd nameTag="Tunisia" />
            <Cardd nameTag="Turkey" />
            <Cardd nameTag="Turkmenistan" />
            <Cardd nameTag="Tuvalu" />
            <Cardd nameTag="Uganda" />
            <Cardd nameTag="Ukraine" />
            <Cardd nameTag="United Arab Emirates" />
            <Cardd nameTag="United Kingdom" />
            <Cardd nameTag="United States of America" />
            <Cardd nameTag="Uruguay" />
            <Cardd nameTag="Uzbekistan" />
            <Cardd nameTag="Vanuatu" />
            <Cardd nameTag="Vatican City" />
            <Cardd nameTag="Venezuela" />
            <Cardd nameTag="Vietnam" />
            <Cardd nameTag="Yemen" />
            <Cardd nameTag="Zambia" />
            <Cardd nameTag="Zimbabwe" />
        </div>
    )
}
